version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    cpus: "4"
    volumes:
      - /mnt/yolosolo/configs/jellyfin/config:/config
      - /mnt/yolosolo/caches/jellyfin:/cache
      - /mnt/yolosolo/rasptemp:/media
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
        #- /dev/vchiq:/dev/vchiq
      - /dev/vcsm-cma:/dev/vcsm-cma
    ports:
      - 8096:8096
    restart: 'unless-stopped'
    labels:
      easyhaproxy.http.host: "jellyfin.rasppi.firewood"
      easyhaproxy.http.localport: "8096"

      easyhaproxy.remote.host: "jellyfin.home.bvwyngaard.co.za"
      easyhaproxy.remote.localport: "8096"
