version: "2.1"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /mnt/yolosolo/configs/transmission:/config
      - /mnt/yolosolo/downloads:/downloads
      - /mnt/yolosolo/watch/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /mnt/yolosolo/configs/sonarr:/config
      - /mnt/yolosolo/rasptemp/series:/tv #optional
      - /mnt/yolosolo/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /mnt/yolosolo/configs/radarr:/config
      - /mnt/yolosolo/rasptemp/movies:/movies #optional
      - /mnt/yolosolo/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /mnt/yolosolo/configs/prowlarr/:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Johannesburg
    volumes:
      - /mnt/yolosolo/configs/bazarr:/config
      - /mnt/yolosolo/rasptemp/movies:/movies #optional
      - /mnt/yolosolo/rasptemp/series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped